### ISSUE TITLE
Minta projektek - Examples

### ISSUE THREAD

**Issue by speter555** [i-Cell-Mobilsoft-Open-Source/coffee#18]
Sziasztok,

Lehetne kérni esetleg mintaprojektet hogy egyes részeit hogyan is kellene használni a coff:ee-nak?
Esetleg a wdc-backend ilyen irányú felokosítása?

Üdv,
Péter

**Comment by rombow** [comment]
Később mindenképp lesz ilyen, tervezünk egy example projektet, csak erőforrás hiányban vagyunk ezzel. Most csak belsős projektek vannak.
