### ISSUE TITLE
coffee.app.name valtozo hianyaban nem indulnak el az alkalmazasok

### ISSUE THREAD

**Issue by cserhatit** [i-Cell-Mobilsoft-Open-Source/coffee#191]
"A 'coffee.app.name' konfigurációs paramétert be lehet állítani a futtatandó modulok esetében, de nem kötelező, a 'java:app/AppName' a default."

Sajnos ennek a valtozonak a hianyaban nem indul el az alkalmazas

**Comment by Balazs-Joo** [comment]
Thorntail esetében nem indul az alkalmazás, Wildfly esetén pedig futás közben jelentkezik a hiba
Property coffee.app.name is required but the value was not found or is empty
