### ISSUE TITLE
ConfigurationHelper használata nem RequestScope-ban

### ISSUE THREAD

**Issue by speter555** [i-Cell-Mobilsoft-Open-Source/coffee#20]
ConfigurationHelper osztályban a 
`private BaseRequestContainer getRequestContainer()` metódusban az
`Instance<BaseRequestContainer> instance = CDI.current().select(BaseRequestContainer.class);` elszáll ha nem RequestScoped van, hanem pl egy Event kezelése közben szeretnénk használni az osztályt.

**Comment by rombow** [comment]
A ConfigurationHelper direkt egy request scope szintű cache a konfigokra, főleg azokra melyeknek megszerzése kölcséges (ETCD, DB), de persze a többi fajtánál is jól jön.

Ha egy új szálban akarjuk használni aminek nincs request scope-ja akkor 3 megoldás lehetséges:
- ApplicationConfiguration használata ami 30 percenként olvassa újra a konfigot
- Sima microprofile @ConfigProperty vagy inline Config olsztály használata
- a szálban indítunk egy request scope-t

Ha tisztázódott a kérdés kérlek zárt az issue-t, ha nem egyeztesünk tovább.

Imi

**Comment by speter555** [comment]
Köszönöm szépen!
