### ISSUE TITLE
Production ProjectStage esetében a hiba válasz (BaseExceptionResultType) causedBy értéke nincs töltve

### ISSUE THREAD

**Issue by tamkarcsi** [i-Cell-Mobilsoft-Open-Source/coffee#210]
Production ProjectStage esetében a BaseExceptionResultType causedBy nincs töltve, erre döntési logikák épülhetnek, ezért szükséges mindig tölteni.

A DefaultExceptionMessageTranslator.addCommonInfo metódusában kell módosítani a causedBy töltését ki kell venni a putExceptionToResponse vizsgálat alól.

**Comment by rombow** [comment]
Eles kornyezetekben nem szabad stacktrace-t valaszolni mert az biztonsagi problemakba vezet, sokmindent elarulhat a backend rendszerbol. Tehat a hibakod es a nyelvesitett szoveg eleg kell hogy legyen, persze a logban ott van minden tovabbra is. Maga a BaseExceptionResultType-ra nem szabad semmifele logikat epiteni senkinek, csakis a http statusz vagy hibakodra

**Comment by tamkarcsi** [comment]
Mivel a kliens hívások a RestClientResponseException-be lettek csomagolva a kiváltó ok lejjebb került e szinttel a causedBy-ba, pl. BONotFoundException, amire épül logika, de Production akkor nem jól működik megfelelően.

**Comment by rombow** [comment]
Ez inkabb kliens kezelesi problema. Ha valami belso hivas elszal a MS kozott akkor semmikeppen sem kerulhet ki annak a hibakodja, mindig valami "boritek" hibakoddal kell valaszolni. Egyedi uzenet is lehet, de nem mindenre kiterve az mar tervezesi hiba
