### ISSUE TITLE
io.etcd.jetcd.Client példány kezelése

### ISSUE THREAD

**Issue by speter555** [i-Cell-Mobilsoft-Open-Source/coffee#225]
io.etcd.jetcd.Client producere Application szintű, emiatt ha valami miatt megszakad a kapcsolat az etcd-vel, akkor nem áll helyre az etcd kliens, ezen lenne jó javítani, hogy ne az alkalamzást kelljen újraindítani.

**Comment by martin-nagy** [comment]
Próbálkoztam a reprodukálásával, de nem sikerült előhoznom a hibát, sem a Config-on (DefaultEtcdConfigSource) keresztül, sem az etcd klienst közvetlenül használva. Az alábbi példakód nem ad vissza hibát, miután az etcd szervert visszaindítom. 
@speter555 tudnál esetleg több infót adni a reprodukálásához?

```java
@Inject
private io.etcd.jetcd.Client etcdClient;

public void test() {
    while (true) {
        try {
            TimeUnit.SECONDS.sleep(1);
            PutResponse putResponse = etcdClient.getKVClient()
                    .put(ByteSequence.from("foo".getBytes()), ByteSequence.from("bar".getBytes()))
                    .get();
            System.out.println(putResponse);
        } catch (InterruptedException | ExecutionException e) {
            System.err.println(e.getMessage());
        }
    }
}
```

**Comment by martin-nagy** [comment]
Egyenlőre annyit találtam, hogy ha etcd hívásnál hálózati hiba van, akkor az etcd kapcsolat `io.grpc.ConnectivityState#TRANSIENT_FAILURE` állapotba kerül, és folyamatosan próbál, egyre nagyobb időközökkel újracsatlakozni a szerverhez (`io.grpc.internal.ExponentialBackoffPolicy`). A kapcsolat addig nem kerül `READY` státuszba, amíg a backoff policy egy tick-je át nem billenti, hiába állt helyre már egy ideje a szerver. Emiatt még percekig használhatatlan marad a kliens.
Nem lehet, hogy csak ennyi a probléma?

**Comment by speter555** [comment]
Ezt nem tudom sajnos megmondani.

**Comment by czenczl** [comment]
https://github.com/i-Cell-Mobilsoft-Open-Source/coffee/issues/229 verzio frissítése a következőt megoldja:
local service indítása + vpn off + war deploy a jetcd 0.5.0 verzióval beakad a service, és nem is javul meg.
0.6.1 esetében magától helyreáll az etcd kapcsolat.

infok:
https://gitmemory.cn/repo/grpc/grpc-java/issues/8574
https://github.com/etcd-io/jetcd/pull/814
