### ISSUE TITLE
ConfigUtil osztály nem kezeli a profilozást

### ISSUE THREAD

**Issue by speter555** [i-Cell-Mobilsoft-Open-Source/coffee#247]
Etcd kapcsolatot ezen keresztül van lekérdezve, és csak a microprofile-config.properties -ig olvas, ha van egy microprofile-config-profil100.yml azt nem tudja felolvasni, így nem módosítható.

Megoldható lenne hogy a profil felül írhassa?

**Comment by rombow** [comment]
Ugytudom az etcd beallitasokat a default forrasokbol lehet neki csak beadni, tehat properties, system es env param. Elegge paradox lenne ha mashol is kereshetne ezeket, mondjuk sajat magaban, de nem tud casatlakozni mire... Ettol fuggetlenul nemtudom mennyire lenne megoldhato hogy tuleljen ilyen helyzetet is
