### ISSUE TITLE
Karakterkódolás JSON deszerializáláskor

### ISSUE THREAD

**Issue by Spatrik95** [i-Cell-Mobilsoft-Open-Source/coffee#252]
Egy olyan hibát találtunk, hogy ha egy POST request body-ban magyar ékezetes karakterek vannak, akkor azok objektummá való deszerializálásakor rosszul lesznek kódolva, így elvesznek. (pontosabban kérdőjelek lesznek helyettük)

A problémát úgy oldottuk meg projekt szinten, hogy leszármaztattuk a `JsonBodyReaderBase` osztályt és megadtuk az `InputStream`-nek explicit az UTF-8 kódolást.

Konkrét sor: https://github.com/i-Cell-Mobilsoft-Open-Source/coffee/blob/master/coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/validation/json/JsonMessageBodyReaderBase.java#L140

A megoldás, amit alkalmaztunk:
```
return JsonUtil.toObjectGson(new InputStreamReader(entityStream, StandardCharsets.UTF_8), type);
```

_Használt JDK: temurin-11.0.14.1_

**Comment by rombow** [comment]
Ami a http hederben van contentype kodolas az biztos UTF-8-ra van allitva?
