### ISSUE TITLE
Forditasi javadoc hibak javitasa

### ISSUE THREAD

**Issue by rombow** [i-Cell-Mobilsoft-Open-Source/coffee#29]
Ha deploy vagy release tortenik, a javadoc generalas nemely osztalyan hibakat jelent. Ezek most skippelve vannak, de jo volna kijavitani oket. Ha ki lesznek javitva akkor lessz egy ellenorzes ami a commitnal nem fogja az ujabb hibas commenteket beengedni

Reprodukalas:
`mvn javadoc:jar`

**Comment by speter555** [comment]
Ha még senki nem kezdett bele ebbe a szép nagy feladatba, én elkezdeném, de szerintem modulonként kéne max haladni (még lehet az is sok). Én a coffee-cdi-t kezdem el.

**Comment by rombow** [comment]
De mar elkezdtek, de nemtudom mennyire haladott
