### ISSUE TITLE
TransactionHelper továbbfejlesztése jakarta tranzakció által nyújtott lehetőségekkel

### ISSUE THREAD

**Issue by bcsabi** [i-Cell-Mobilsoft-Open-Source/coffee#387]
Felmerült igényként, hogy a TransactionHelper tudjon meglévő tranzakció helyett saját tranzakciót nyitni és abban futtatni az átadott kódot. Ez praktikus lehet olyan esetekben például ha egy tranzakción belül több mentés van, de bizonyos mentéseket nem akarunk rollbackelni hiba esetén. Habár kódszervezéssel ez is megoldható, de a jakarta tranzakcióban erre van megoldás, a `REQUIRES_NEW` opció. Így a jakarta ee 10 átállás teret adhatna ezen plusz lehetőség bevezetésére, hogy ezzel is okosabb legyen a TransactionHelper és szélesebb körben biztosítson megoldást a jakarta tranzakcióval.

Ezért első körben szeretném a TransactionHelper-t továbbfejleszteni, hogy lefedje a jakarta tranzakció `REQUIRES_NEW` lehetőségét.

Ezenkívül ha bármilyen más jakarta tranzakciós opcióra igény lenne, azok felvétele is megtörténhetne.

**Comment by rombow** [comment]
Ezt az igenyt lehetne akar a https://github.com/i-Cell-Mobilsoft-Open-Source/coffee/issues/371 issue-ra felkesziteni

**Comment by speter555** [comment]
Közben a 371 meg lett oldva.

**Comment by czenczl** [comment]
Nekem felemás érzésem van ezzel a fejelsztéssel kapcsolatban. A tranzakciókezelőt eddig próbáltuk a lehető legegyszerűbben tartani, mert elég sok komplikacióval talalkoztunk pl nested tranzakciók esetében.
Sokszor nehéz átlátni azokat az eseteket amikor több szinten kezelünk tranzakciókat. Én jobbnak tartom ha ez helyes kód szervezéssel van megoldva, mert akkor egyértelmű a működés.
Ugyanakkor értem hogy valahol szükség lehet rá, ezekből az esetekből https://github.com/jakartaee/transactions/blob/master/api/src/main/java/jakarta/transaction/Transactional.java#L99 csak a "REQUIRES_NEW" működéssel szeretnétek bővíteni, vagy később a többivel is? Ehhez nagyon pontosan át kell tudni adni hogy ezekben az esetekben mire kell számítani.

**Comment by bcsabi** [comment]
Nekem is kettős érzéseim voltak és vannak, főleg mióta beszéltünk erről és én is jobban átgondoltam.
Alapjáraton a `TransactionHelper`-t akkor fogjuk használni, amikor nincs tranzakció, de valamit mégis tranzakcióban szeretnénk futtatni. Maga a `REQUIRES_NEW` ennek az ellentéte lenne olyan módon, hogy van tranzakció, de az adott kódot különálló tranzakcióban akarjuk futtatni.

A tranzakció kezelés tényleg problémás téma és jobb tisztán tartani, ezért én is inkább a jelenlegi működés használatát és a megfelelő kódszervezést részesíteném előnyben.

Maga az issue egy másik projektről érkező igény szerint jött fel és mivel a coffee általános megoldásokat ad, így gondoltam, hogy ezzel is okosítható lenne maga a `TransactionHelper`. Tehát ha ez a módszer valahol használva van, akkor kapjon egy általános megoldást itt kiemelve.

Azonban tényleg több bonyodalmat, fejtörést és kevésbé átlátható kódot tud a használata okozni.
Ezért én rátok bíznám, hogy mennyire van ténylegesen igény a bevezetésére.

`"REQUIRES_NEW" működéssel szeretnétek bővíteni, vagy később a többivel is?`
A `REQUIRES_NEW` is elég problémás és ténylegesen csak plussz lehetőségként gondolnék rá, ott ahol feltétlen muszáj és szükséges (ha van ilyen), a többi talán ennél is problémásabb így inkább mostani fejjel afelé hajlanék, hogy egyikkel sem.
