### ISSUE TITLE
EtcdService timout kezelés

### ISSUE THREAD

**Issue by czenczl** [i-Cell-Mobilsoft-Open-Source/coffee#418]
Felfutásnál véletlenszerűen timeout exception keletkezik amikor kulcsot akarunk elkérni, további hibát nem okoz, de a probléma abból fakad hogy a Client és a lekérés timeout értékei nem egyeznek.

https://github.com/i-Cell-Mobilsoft-Open-Source/coffee/blob/master/coffee-module/coffee-module-etcd/src/main/java/hu/icellmobilsoft/coffee/module/etcd/service/EtcdService.java#L116

vs

https://github.com/i-Cell-Mobilsoft-Open-Source/coffee/blob/master/coffee-module/coffee-module-etcd/src/main/java/hu/icellmobilsoft/coffee/module/etcd/util/EtcdClientBuilderUtil.java#L65

Meg kell nézni pontosan melyik konfig eltérés okozza az időkülönbséget amiből a hiba fakad.

**Comment by speter555** [comment]
A másodiknál null az alap, lehet azzal okozódott a probléma :(
