### ISSUE TITLE
Move ValidateXML and ValidateXMLs annotation to coffee-dto-base

### ISSUE THREAD

**Issue by rombow** [i-Cell-Mobilsoft-Open-Source/coffee#511]
We need move ValidateXML and ValidateXMLs annotations to coffee-dto-base are required to clean up the dependency structure of the implementation project

**Comment by speter555** [comment]
hu.icellmobilsoft.coffee.cdi.annotation.Version függőség miatt akkor viszont a coffee-dto-base megkapná a 
<dependency>
			<groupId>hu.icellmobilsoft.coffee</groupId>
			<artifactId>coffee-cdi</artifactId>
			<version>${project.version}</version>
		</dependency>
függőséget, amiben ott lenne  a nagyon sok jakarta függőség, a jboss-logging és a microprofile-config-api is. Kérdés hogy így is jó átteni?
