### ISSUE TITLE
JsonB support

### ISSUE THREAD

**Issue by rombow** [i-Cell-Mobilsoft-Open-Source/coffee#512]
We need jsonb support in coffee:
* FieldOnlyVisibilityStrategy
```
public class FieldOnlyVisibilityStrategy implements PropertyVisibilityStrategy {

    @Override
    public boolean isVisible(Field field) {
        return true;
    }

    @Override
    public boolean isVisible(Method method) {
        return false;
    }
}
```
* JsonbUtil
```
        JsonbConfig config = new JsonbConfig()
                // property visibility strategy setting
                .withPropertyVisibilityStrategy(new FieldOnlyVisibilityStrategy())
        return JsonbBuilder.newBuilder().withConfig(config).build();

```

**Comment by speter555** [comment]
Érdekesség a teszthez:
jakarta.json.bind.JsonbBuilder newBuilder() metódusa a jakarta.json.bind.spi.JsonbProvider.provider() -t hívja meg, amiben a default provider: org.eclipse.**yasson**.JsonBindingProvider . Emiatt a teszthez szükséges ez, de a yasson amúgy a WF-ben is bele van téve natívan, érdekes lehet hogy a coffee is ezt használja

**Comment by speter555** [comment]
Quarkus miatt kérdéses volt, érdemes megcsinalni úgy, hogy alapvetően csak a minimális megoldás legye  default, de configból dolgozhasson a folyamat, így kód változtatás nélkül lehessen configolni.
Quarkus máshogy oldja meg a jsonb configurációt.
