### ISSUE TITLE
AbstractEntity.toString() fgv "stream" típusok kezelése 

### ISSUE THREAD

**Issue by attila-kiss-it** [i-Cell-Mobilsoft-Open-Source/coffee#536]
A jelenlegi implementáció csak a byte[] típust kezeli speciálisan, azaz nem olvassa a mező konkrét értékét ilyen típusú oszlop esetén.
Hasonlóan kellene eljárni Blob/Clob esetén is.

**Comment by rombow** [comment]
Biztos ki kellene rakni toString-be a binaris es a nagy tartalmakat?

**Comment by attila-kiss-it** [comment]
Épp ellenkezőleg, ki akarom venni a toString-ből a bináris tartalmakat, ahogy a byte[] is ki van szedve.

**Comment by rombow** [comment]
Jah oke, nem volt teljsen tiszta mi a cel
