### ISSUE TITLE
org.apache.deltaspike.data.api.Modifying annotáción lévő @Deprecated eltávolítása

### ISSUE THREAD

**Issue by norbertbarocsi** [i-Cell-Mobilsoft-Open-Source/coffee#597]
jakarta.persistence.Query.executeUpdate() aktiválásához a következőknek kell teljesülni

- metóduson szerepeljen a `@Modifying` annotáció és void vagy int vagy Integer legyen a visszatérési értéke

**vagy**

- a metódus prefixe **"removeBy"** vagy **"deleteBy"** elnevezésekkel kezdődjön

Update metódusoknál problémát okoz, ha törlésre kerül az annotáció, hiszen ott a metódus prefixe nem a szükséges elnevezésekkel fog kezdődni.

Delete metódusoknál pedig az annotáció hiányában és a nem megfelelő prefix használatánál is gondot jelent.

**Comment by czenczl** [comment]
Task után a https://github.com/i-Cell-Mobilsoft-Open-Source/backend-sampler projektbe vegyünk fel példákat a használatára.

**Comment by sisak** [comment]
#597 closed
