### ISSUE TITLE
LogContainer minden String msg és Throwable t paraméteres metódusában az msg nincs használva

### ISSUE THREAD

**Issue by speter555** [i-Cell-Mobilsoft-Open-Source/coffee#61]
Az AppLogger osztályban ahol a Throwable paraméter van loggolva ott a paraméterben kapott msg nincs használva.
Vagy ki kéne azt is logba írni, vagy ki kéne venni mint felesleges paraméter.

**Comment by rombow** [comment]
En nem latok ilyent, ki tudnad pontosabban fejteni?

**Comment by speter555** [comment]
Erre gondolok:
```

    public void warn(String msg, Throwable t) {
        String message = getFullStackTrace(t);
        logs.add(new Log(LogLevel.WARN, message));
    }
```

Megkapja az msg string paraméteret de nincs felhasználva.

**Comment by speter555** [comment]
Itt is javítom, nem AppLogger hanem LogContainer -t kellett volna írnom.

**Comment by rombow** [comment]
Szuper. Ha már hozzá lesz nyúlva, akkor légyszíves az esemény ideje is legyen kiegészítve amikor el van tárolva a hiba a gyűjtőben...

**Comment by speter555** [comment]
@rombow mi legyen az időpont pontosan? LocalDateTime vagy OffsetDateTime ?

**Comment by rombow** [comment]
> @rombow mi legyen az időpont pontosan? LocalDateTime vagy OffsetDateTime ?
> Valamint elég lesz hogyha a Log osztályba a konstruktorba teszem bele az időpontot? Valamint kiírásnál van erre épülő logika vajon? Vagy jó lesz ez: [2020-09-14T08:11:07.8320909+02:00]CUSTOM:Üzenet

szerintem ebben az esetben eleg a LocalDateTime
