### ISSUE TITLE
LogContainer metódusainak összevonása

### ISSUE THREAD

**Issue by speter555** [i-Cell-Mobilsoft-Open-Source/coffee#62]
Egyes metódusok lefedik egymást, úgy hogy a működésük is ugyan az, így egyszerűseíteni lehetne az osztályt.

Pl.:
```
 public void info(String format, Object... arguments)
 public void info(String format, Object arg)
 public void info(String format, Object arg1, Object arg2)
```
Maradna az első, és abba a másik kettő is beletartozik.

**Comment by rombow** [comment]
A 1.1.0 verzióban átesett a logger egy refacton. A master ágon lévő kódokat nézed? Mert én nem látok már ilyeneket.

**Comment by speter555** [comment]
Bocsánat, benéztem a fájlt :( LogContainer-t kellett volna írnom, nem AppLogger-t

**Comment by rombow** [comment]
Oké köszi a pontosítást
