### ISSUE TITLE
@ConfigDoc - új oszlopok indítási vagy futásidőben felülírható konfiguráció jelölésére

### ISSUE THREAD

**Issue by mate-biro** [i-Cell-Mobilsoft-Open-Source/coffee#644]
@ConfigDoc annotációban legyen lehetőség megadni, hogy az adott konfig kulcs az indítási időben értelmezett, vagy futásidőben felülírható, és ez jelenjen meg a táblázatban, új oszlopokban. pl:

![Screenshot_20240328_163106](https://github.com/i-Cell-Mobilsoft-Open-Source/coffee/assets/72201116/76a348a6-f040-4af9-b03d-d9642c6625ce)

```
=== test keys
[cols="1,2,1,1,1,1,1",options=header,stripes=even]
|===
|Key|Source|Description|Default value|Since|Startup|Runtime overridable
|test.key.one|org.test.constants.ConfigKeys|#1 test key|| ^|[X] ^|[ ]
|test.key.two|org.test.constants.ConfigKeys|#2 test key|| ^|[ ] ^|[X]
|===
```

**Comment by rombow** [comment]
Esetleg hogyha 1 uj oszlop jonne letre amiben lenne akar tobb piktogram, symbol, emoji vagy valami egyeb, amivel lehet utalni a tulajdonsagokra...

**Comment by Adigolyo** [comment]
Megbeszéltek alapján első körben most egy oszlop marad `Features` névvel és a megfelelő emojik/piktogrammok kerülnek beírásra, emojik dokumentálva lesznek melyik mit jelent. A jövőben érdemes lesz ezt a táblázatot refaktorálni, kevesebb oszlop több infó a `description`-be lenyithatóan.
