### ISSUE TITLE
SaxParseBaseException, InvalidRequestException deprecated vizsgalata

### ISSUE THREAD

**Issue by rombow** [i-Cell-Mobilsoft-Open-Source/coffee#70]
Az említett 2 exception célját már pótolja a XsdProcessingException. Ennek fényében meg kell vizsgálni hogy kivezetésre jelölhető-e

**Comment by magyari-adam** [comment]
Mindkét Exception unused jelenleg.

**Comment by rombow** [comment]
Rendben, akkor mindkettőt Deprecated-re kellene jelolni, ha nincs másnak ötlete valami újrahasznosításra...
